server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:

  application:
    name: attornatus-technical-test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:TECHNICAL_TEST_DATABASE?createDatabaseIfNotExist=true
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
    platform: org.hibernate.dialect.h2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  paths-to-exclude:
    - /addresses/search/findByPerson
    - /addresses/search/findByPersonAndId
    - /addresses/search/updateIsMainById
    - /addresses/search/updateIsMainByPersonAndId
    - /addresses/{id}/person
  paths-to-match:
    - /persons/update
    - /persons/register
    - /persons/find-by-id/{personId}
    - /persons/find-all
    - /addresses/{personId}/{addressId}
    - /addresses/register
    - /addresses/find-by-person/{personId}
